<?php

function lom_user_account_entity_view($entity, $type, $view_mode, $langcode){
    
    if($type == 'user'){
        $output = drupal_get_form('lom_user_account_form',$entity->uid);
        $body   = drupal_render($output);
            
        $entity->content['field_last_name']['#access'] = FALSE;
        // raha vao tsy ao anatin'ilay field ilay atao ao anatin'ilay content eto
        // de tsy mety iseho mihitsy ilay izy
        $entity->content['field_first_name'] = array(
            '#prefix' => '<div>',
            '#suffix' => '</div>',
            '#markup' => $body,
            '#access' => TRUE,
        );
    }
}

function lom_user_account_form($form, &$form_state,$user_id) {
    
    if($user_id != 0 && $user_id != NULL){
        
        $form['#tree'] = TRUE;

        module_load_include('php','wrappers_custom','includes/user/UserUserWrapper');
        $user    = new UserUserWrapper($user_id);
        $account = user_load($user_id);
        
        $form['first_name'] = array(
            '#type'  => 'markup',
            '#markup'=> t('Fisrt Name : ').$user->getFirstName(),
            '#prefix' => '<div>',
            '#suffix' => '</div>',
        );
        
        $form['last_name'] = array(
            '#type'  => 'markup',
            '#markup'=> t('Last Name : ').$user->getLastName(),
            '#prefix' => '<div>',
            '#suffix' => '</div>',
        );
        
        $form['user_email'] = array(
            '#type'  => 'markup',
            '#markup'=> t('E-mail : ').$account->mail,
            '#prefix' => '<div>',
            '#suffix' => '</div>',
        );
        
        $form['lom_settings'] = array(
            '#type'  => 'markup',
            '#markup'=> l(t('Settings'), '/lom_settings'),
        );

        return $form;
    }
}