<?php


function lom_services_menu(){
    $items = array();
    $items['lom_services/%'] = array(
        'page callback' => '_lom_services_changed_photographs',
        'access callback'   => TRUE,
        'page arguments' => array(1),
    );
    return $items;
}


/*
 * hook_ctools_plugin_api
 * 
 * Ilaina ity function ahafahana mi-declarer service aty @ code fa tsy any @ interface
 */

function lom_services_ctools_plugin_api($owner,$api){
    if ($owner == 'services' && $api == 'services') {
        return array(
            'version' => 3,
        );
    }
}
/*
 * Function mi-declarer endpoint
 */
function lom_services_default_services_endpoint() {
    
    $endpoints = array();
    
    $endpoint = new stdClass();
    $endpoint->disabled = FALSE; /* Edit this to true to make a default endpoint disabled initially */
    $endpoint->api_version = 3;
    $endpoint->name = 'lom_node_services';
    $endpoint->server = 'rest_server';
    $endpoint->path = 'lom_endpoint/api/v1/services';
    $endpoint->authentication =array();// array( 'services' => 'services',);
    $endpoint->server_settings = array(
        'formatters' => array(
            'json' => TRUE,
            'bencode' => FALSE,
            'jsonp' => FALSE,
            'php' => FALSE,
            'xml' => FALSE,
        ),
        'parsers' => array(
            'application/json' => TRUE,
            'application/vnd.php.serialized' => FALSE,
            'application/x-www-form-urlencoded' => FALSE,
            'application/xml' => FALSE,
            'multipart/form-data' => FALSE,
            'text/xml' => FALSE,
        ),
    );
    $endpoint->resources = array(
        'lom_node_services' => array(
            'actions' => array(
                'changed_species' => array( //Export to iPhone
                    'enabled' => '1',
                ),
                'changed_places' => array( //Export to iPhone
                    'enabled' => '1',
                ),
                'changed_families' => array( //Export to iPhone
                    'enabled' => '1',
                ),
                'changed_photographs' => array( //Export to iPhone
                    'enabled' => '1',
                ),
                'changed_maps' => array( //Export to iPhone
                    'enabled' => '1',
                ),
                
            ),
        ),
        
    );
    
    $endpoint->debug = 1;

    $endpoints[] = $endpoint;

    return $endpoints;
      
}


/*
 * hook_services_resources
 */


function lom_services_services_resources() {
    return array(
        
    'lom_node_services'=> array(
        
        'actions' => array(
            
                'changed_species' => array(

                    'help' => t('Export recently changed species to iPhone'),
                    'callback' => '_lom_services_changed_species',
                    'access callback' => '_lom_services_access_permission',
                    'access arguments append' => FALSE,
                    'args' =>array(
                                array(
                                    'name' => 'from_date', 
                                    'optional' => FALSE, //mandatory parameter
                                    'source' => array('param' => 'from_date'),
                                    'type' => 'int', 
                                    'description' => 'User uid',
                                ),
                    ),
                ),
            
                'changed_places' => array(

                    'help' => t('Export recently changed places to iPhone'),
                    'callback' => '_lom_services_changed_places',
                    'access callback' => '_lom_services_access_permission',
                    'access arguments append' => FALSE,
                    'args' =>array(
                                array(
                                    'name' => 'from_date', 
                                    'optional' => FALSE, //mandatory parameter
                                    'source' => array('param' => 'from_date'),
                                    'type' => 'int', 
                                    'description' => 'User uid',
                                ),
                    ),
                ),
            
                'changed_families' => array(

                    'help' => t('Export recently changed families to iPhone'),
                    'callback' => '_lom_services_changed_families',
                    'access callback' => '_lom_services_access_permission',
                    'access arguments append' => FALSE,
                    'args' =>array(
                                array(
                                    'name' => 'from_date', 
                                    'optional' => FALSE, //mandatory parameter
                                    'source' => array('param' => 'from_date'),
                                    'type' => 'int', 
                                    'description' => 'User uid',
                                ),
                    ),
                ),
            
                'changed_photographs' => array(

                    'help' => t('Export recently changed photographs to iPhone'),
                    'callback' => '_lom_services_changed_photographs',
                    'access callback' => '_lom_services_access_permission',
                    'access arguments append' => FALSE,
                    'args' =>array(
                                array(
                                    'name' => 'from_date', 
                                    'optional' => FALSE, //mandatory parameter
                                    'source' => array('param' => 'from_date'),
                                    'type' => 'int', 
                                    'description' => 'User uid',
                                ),
                    ),
                ),
            
                'changed_maps' => array(

                    'help' => t('Export recently changed maps to iPhone'),
                    'callback' => '_lom_services_changed_maps',
                    'access callback' => '_lom_services_access_permission',
                    'access arguments append' => FALSE,
                    'args' =>array(
                                array(
                                    'name' => 'from_date', 
                                    'optional' => FALSE, //mandatory parameter
                                    'source' => array('param' => 'from_date'),
                                    'type' => 'int', 
                                    'description' => 'User uid',
                                ),
                    ),
                ),
            
            ),
        ),//-- ACTIONS ---//
    );
    
}

/**
 * Ito ny function mametra ny access @ ity webservice ity. Raha tsy authenticated tsy mahazo miditra
 * @return boolean
 */
function _lom_services_access_permission(){
    if(user_is_logged_in()){
        return TRUE;
    }
    return TRUE;
}
    
/*
 * Maka izay species changed vao haingana
 */
function _lom_services_changed_species($from_date){
    
    if($from_date != NULL){
        
        module_load_include('php','wrappers_custom','includes/node/LomSpeciesNodeWrapper');
        $data = LomSpeciesNodeWrapper::allSpecies($from_date);
        drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');
        return $data; 
        
    }
}

/*
 * Maka izay species changed vao haingana
 */
function _lom_services_changed_places($from_date){
    
    if($from_date != NULL){
        
        module_load_include('php','wrappers_custom','includes/node/BestPlacesNodeWrapper');
        $data = BestPlacesNodeWrapper::allPlaces($from_date);
        drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');
        return $data; 
        
    }
}

/*
 * Maka izay family changed vao haingana
 */
function _lom_services_changed_families($from_date){
    
    if($from_date != NULL){
        
        module_load_include('php','wrappers_custom','includes/node/LomFamilyNodeWrapper');
        $data = LomFamilyNodeWrapper::allFamilies($from_date);
        drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');
        return $data; 
        
    }
}

/*
 * Maka izay photo changed vao haingana
 */
function _lom_services_changed_photographs($from_date){
    
    if($from_date != NULL){
        
        module_load_include('php','wrappers_custom','includes/node/LomPhotographNodeWrapper');
        $data = LomPhotographNodeWrapper::allPhotographs($from_date);
        drupal_add_http_header('Content-Type', 'application/json; charset=UTF-8');
        return $data; 
        
    }
}

/*
 * Maka izay map changed vao haingana
 */
function _lom_services_changed_maps($from_date){
    
    if($from_date != NULL){
        
        module_load_include('php','wrappers_custom','includes/node/LomMapNodeWrapper');
        $data = LomMapNodeWrapper::allMaps($from_date);
        drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');
        return $data; 
        
    }
}


